# fly.toml app configuration file generated for population-map-bot on 2024-01-11T01:11:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "population-map-bot"
primary_region = "lax"

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
