# fly.toml app configuration file generated for population-map-density-bot on 2023-11-03T17:43:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "population-map-density-bot"
primary_region = "lax"

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="mapbot"
  destination="/mnt/mapbot"